// MOVIES
export const FETCH_MOVIES_REQUEST = "TRENDING_MOVIES_REQUEST";
export const TRENDING_SUCCESS = "TRENDING_SUCCESS";
export const ACTION_MOVIES_SUCCESS = "ACTION_MOVIES_SUCCESS";
export const ANIMATION_MOVIES_SUCCESS = "ANIMATION_MOVIES_SUCCESS";
export const THRILLER_MOVIES_SUCCESS = "THRILLER_MOVIES_SUCCESS";
export const TOP_RATED_MOVIES_SUCCESS = "TOP_RATED_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "TRENDING_MOVIES_FAILURE";
// SHOWS
export const FETCH_SHOWS_REQUEST = "TRENDING_SHOWS_REQUEST";
export const TRENDING_SHOWS_SUCCESS = "TRENDING_SHOWS_SUCCESS";
export const ACTION_SHOWS_SUCCESS = "ACTION_SHOWS_SUCCESS";
export const COMEDY_SHOWS_SUCCESS = "COMEDY_SHOWS_SUCCESS";
export const SCIFI_SHOWS_SUCCESS = "SCIFI_SHOWS_SUCCESS";
export const FETCH_SHOWS_FAILURE = "TRENDING_MOVIES_FAILURE";
