export const FETCH_MOVIES_REQUEST = "TRENDING_MOVIES_REQUEST";
export const TRENDING_MOVIES_SUCCESS = "TRENDING_MOVIES_SUCCESS";
export const ACTION_MOVIES_SUCCESS = "ACTION_MOVIES_SUCCESS";
export const ANIMATION_MOVIES_SUCCESS = "ANIMATION_MOVIES_SUCCESS";
export const THRILLER_MOVIES_SUCCESS = "THRILLER_MOVIES_SUCCESS";
export const FANTASY_MOVIES_SUCCESS = "FANTASY_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "TRENDING_MOVIES_FAILURE";
